import unittest
from timed_test import TimedTest
def wc(s):
  counts = {}
  get = counts.get
  for line in s.splitlines():
    for word in line.split(" "):
      #if word in counts:
      #  counts[word] += 1
      #else:
      #  counts[word] = 1
      counts[word] = get(word, 0) + 1 
  return counts 

class TestWordCount(TimedTest):
    def test_wordcount(self):
        reptext = text * 200
        self.time_compare(wc, reptext, repeat=3)

text = """
 Fellow Workers,
     We come before you as Anarchist Communists to explain our principles. We are aware that the minds of many of you have been poisoned by the lies which all parties have diligently spread about us. But surely the persecutions to which we have been and are subjected by the governing classes of all countries should open the eyes of those who love fair play. Thousands of our comrades are suffering in prison or are driven homeless from one country to the other. Free speech - almost the only part of British liberty that can be of any use to the people - is denied to us in many instances, as the events of the last few years have shown.

      The misery around us is increasing year by year. And yet there was never so much talk about labor as there is now, - labor, for the welfare of which all professional politicians profess to work day and night. A very few sincere and honest but impracticable reformers, in company with a multitude of mere quacks, ambitious placehunters, etc., say they are able to benefit labor, if labor will only follow their useless advice. All this does not lessen the misery in the least : look at the unemployed, the victims of hunger and cold, who die every year in the streets of our rich cities, where wealth of every description is stored up.

      Not only do they suffer who are actually out of work and starving, but every working man who is forced to go through the same dreary routine day by day - the slavery and toil in the factory or workshop - the cheerless home, if the places where they are forced to herd together can be called homes. Is this life worth living? What becomes of the intellectual faculties, the artistic inclinations, nay, the ordinary human feeling and dignity of the greatest part of the workers? All these are warped and wasted, without any chance of development, making the wretched worker nothing but a human tool to be exploited until more profitably replaced by some new invention or machine.

      Is all this misery necessary? It is not if you, the wealth producers, knew that there is enough and to spare of food and of the necessaries of life for all, if all would work. But now, in order to keep the rich in idleness and luxury, all the workers must lead a life of perpetual misery and exploitation. As to these facts we are all agreed; but as to the remedy most of you, unfortunately, have not given up trust in Parliament and the State. We shall explain how the very nature of the State prevents anything good coming from it. What does the State do? It protects the rich and their ill-gotten wealth; it suppresses the attempts of the workers to recover their rights, if these attempts are thought dangerous to the rich. Thus idle electioneering, labor politics etc. are not suppressed, but any effective popular demonstration, vigorous strikes as at Featherstone and Hull, Anarchist propaganda, etc., are suppressed or fought against by the vilest means. Moreover, the State pretending thereby to alleviate the sufferings of the poor, grants Royal Commissions on the Sweating System, the Aged Poor, on Labor in general, or select Committees on the Unemployed - which produce heaps of Blue Books, and give an opportunity to the politicians and labor leaders, "to show themselves off." And that is about all. If the workers demand more - there is the workhouse; and if not satisfied with that, the truncheons of the police and the bullets and bayonets of the soldiers face them: - not bread, but lead!

      All political prisoners are of the same value: either they are not kept, even if it could be, or they involve social changes which can only be effected by a revolution, and not by mere votes cast in Parliament. This applies to the promises of Socialist candidates, even if it could be admitted that these candidates could remain uncorrupted by the demoralizing influence of Parliament.

      There can be no true humanity, no true self-respect, without self- reliance. No one can help you if you do not help yourselves. We do not promise to do anything for you, we do not want anything from you, we only appeal to you to co-operate with us to bring about a state of society which will make freedom, well-being possible for all.

      To do this efficiently, we must all be imbued with the spirit of freedom, and this - freedom, and freedom alone - is the fundamental principle of Anarchy.

      Freedom is a necessary condition to, and the only guarantee of, the proper development of mankind. Nature is most beautiful when unfettered by the artificial interference of man. Wild animals are stronger and more harmoniously developed than their domesticated kind, which the exploiting mind of man makes mere instruments of profit by developing chiefly those parts of them which are of use to him. The same threatens to be the case with the human victims of exploitation, if an end is not put to the system which allows the rich and crafty exploiters to reduce the greater part of mankind to a position resembling that of domestic animals - working machines, only fit to do mechanically a certain kind of work, but becoming intellectually wrecked and ruined.

      All who acknowledge this to be the great danger to human progress should carefully ponder over it, and if they believe that it is necessary to ensure by every means the free development of humanity, and to remove by all means every obstacle placed in its path, they should join us and adopt the principles of Anarchism.

      Belief in and submission to authority is the root cause of all our misery. The remedy we recommend: - struggle unto death against all authority, whether it be that of physical force identical with the State or that of doctrine and theories, the product of ages of ignorance and superstition inculcated into the workers minds from their childhood - such as religion, patriotism, obedience to the law, belief in the State, submission to the rich and titled, etc., generally speaking, the absence of any critical spirit in face of all the humbugs who victimise the workers again and again. We can only deal here briefly with all these subjects, and must limit ourselves to touch only on the chief points.

      Economic exploitation - the result of the monopolisation of the land, raw materials and means of production by the capitalists and landlords - is at the bottom of the present misery. But the system which produces it would have long ago broken down if it were not upheld on one hand by the State, with its armies of officials, soldiers and police - the whole machinery of government, in one word; and on the other hand by the workers themselves, who tamely submit to their own spoliation and degradation, because they think it right, owing to a superstious belief in a divine providence inculcated by their masters, or because they desire, by sneaking means, to become exploiters themselves - an object which only one in a thousand can succeed in - or because they have not lost faith in political action or the capacity of the State to do for them that which they are too ignorant to do for themselves. Under these protections the rich classes are enjoying their spoil in safety and comfort.

      It is evident that this system, if to be destroyed at all, must be attacked by the workers themselves, as we cannot expect those who profit by it to cut their own throats, so to say.

      Many still consider the State a necessity. Is this so in reality? The State, being only a machine for the protection and preservation of property, can only obstruct freedom and free development, being bound to

keep up the law and every statute law is an obstacle to progress and freedom.

Laws are of two kinds. They are either simple formulae, derived from the obsevation of phenomena as the so-called laws of nature, the phrasing of which is open to revision with the progress of human know-ledge and the accumulation of fresh material to draw dedcutions from. No authority is required to enforce them, they exist; and every being arranges his conduct in conformity with his knowledge of their action. The phenomenon of fire burning is the result of such a natural law, and all pay attention to it though there is no policeman posted behind every match and fireplace. Here again Nature gives us an example of free development and Anarchy, and in a free society all social facts and necessities would be equally well recognised and acted upon.

But there is the other kind of law. That which is the expression of the will of an unsrupulous minority, who, owing to the apathy and ignorance of the majority, have been able to usurp the means of power and purport to represent the whole people at the time of the enaction of the laws.

The fact that a great number of persons is in favor of something is evidently no guarantee that it is right. Experience, on the contrary, shows that progress is usually brought about by individuals. New discoveries, new lines of human activity are first found and practised by a few, and only gradually adopted by the many. The majority that makes the laws or abides to them will almost always lag behind progress, and the laws made by it will be reactionary from the very beginning. How much more so as time proceeds and new progress is made!

Of course, progress itself laughs at the puny efforts of the usurpers of power to stop its triumphant march. But its apostles and advocates have to suffer much and severely for the enthusiasm and the hope that is within them. Prison and often death itself is their doom; the penalty for having raised the standard of revolt against authority and law, the embodiment of the spirit of oppression.

And the very makers of these laws are forced to admit that their work is useless. Is not the continuous manufacture of new laws going on in the Parliaments of all countries throughout the greater part of this century, and in England for many centuries, a proof of the fact that laws never satisfy anybody, not even those who make them. They know, however, that their legislating is mere mockery and hypocrisy, having no other object but to make the people believe that something is being done for them, and that the public interest is well looked after. The people obey all these laws, whilst the State, in the alleged interest of all, in reality in the interest of the property owners and of its own power, violates them all and commits numberless crimes - which are glorified as deeds of valor committed in the interest of civilisation.

This principle, kept in the background in time of peace, is paraded before the eyes of the people in time of war. A trading company acquiring so-called "rights" in some savage territory, plunders and provokes the natives until they return force by force. Then the State steps in, in the pretended interest of religion and civilisation, slaughters them and annexes their land. The greater the slaughter, the greater the glory for these "heroic" pioneers. Or it may be in a war on a greater scale with a European State, when the workers of one country are let loose against those of another, to murder, plunder and burn homes and villages, and perform such like patriotic deeds of valor and chivalry.

We Anarchists are internationalists, we acknowledge no distinction of nationality or color. The workers of all countries suffer as we do here, and our comrades have everywhere to fight the same battle for freedom and justice. The capitalists are internationally unanimous in persecuting the defenders of freedom and in fleecing the workers. Even England is brought more and more under the sway of a continental police system, the dangers of which the British masses do not see at present, as it is used chiefly against friendless foreign refugees. They are regardless fo the fact that it is but the forerunner of an attack on their own liberties.

The workers as a rule are filled with an unreasoning dislike to the workers of other countries, whom their masters have succeeded in representing to them as their natural enemies, and herein lies one of the main sources of the strength of the capitalist system; a strength which has no other foundation than the weakness and helplessness of the people. It is in the interests of all governments to uphold patriotism, to have their own people ready to fly at the throats of their fellow workers of other nationalities whenever it suits the interests of the employers to open up new markets, or draw the attention of the people away from the contemplation of their own misery, which might drive them to revolt.

Patriotism and religion have always been the first and last refuges and strongholds of scoudrels. The meek and lowly servants of the one blessing - in the name of their God - the infamies committed for the sake of the other, and cursing in the same name the deeds they just now blessed if committed by the enemy.

Religion is mankind's greatest curse! It is absurd to expect that science, in the few years that the State and the priests have left it to a certain extent alone - the stakeor the prison has been too often the reward of its pioneers - should have discovered everything. It would not be worth living in a world where everything had been discovered, analysed and registered. One fact is certain: all so-called religions are the products of human ignorance, mere phantastical efforts of barbarous people to reason out matters which they could not possibly understand without some knowledge of science and scientific methods. The opinion of a savage on the power that works a steam engine, or produces the electric light, is evidently worthless and could be refuted by anyone possessing elementary knowledge. In the same worthless way our forefathers, savages also, reasoned about the phenomena of nature, and came to the naive conclusion that somebody behind the curtains of the sky pulled the strings. This supposed individual they called God and the organic force of man the soul, and endowed it with a separate entity, although that organic force does not possess any more separate entity than that working a clock or a steam hammer. A dim consciousness of this has permeated the mind of most in spite of the fact that religion has been bolstered up by all the forces of authority, because it teaches submission to the law, and as a reward gives cheques drawn on the bank of heaven, which are not more likely to be met than the politician's promises of what he will do when he is returned for Parliament. Religion is the most deadly enemy to human progress. It has always been used to poison the mind and deaden the judgment of the young, thus making grown up people accept all its absurdities because they are familiarised with them in their youth.

      Unfortunately, religion is not kept out of the labor movement. Priests and parsons, who should be a horror to mankind, as their presence adds an additional element of corruption, sneak into it, and labor politicians use their services as the Liberals and Tories do. There is actually in existence a body of persons who prostitute the noble word "Labor" by coupling it with the disgusting word "Church", forming the "Labor Church", which is looked upon favorably by most of the prominent labor leaders. Why not start a "Labor Police"?

      We are Atheists* and believe that man cannot be free if he does not shake off the fetters of the authority of the absurd as well as those of every other authority. Authority assumes numerous shapes and disguises, and it will take a long period of development under freedom to get rid of all. To do this two things are wanted, to rid ourselves of all superstition and to root out the stronghold of all authority, the State.

      We shall be asked what we intend to put in place of the State. We reply, "Nothing whatever!" The State is simply an obstacle to progress; this obstacle once removed we do not want to erect a fresh obstruction.

      In this we differ essentially from the various schools of State Socialists, who either want to transform the present State into a benevolent public-spirited institution (just as easy as to transform a wolf into a lamb), or to create a new centralised organisation for the regulation of all production and consumption, the so-called Socialist society. In reality this is only the old State in disguise, with enormously strengthened powers. It would interfere with everything and would be the essence of tyranny and slavery, if it could be brought about. But, thanks to the tendency of the ways and means of production - which will lead to Anarchy - it cannot.

      But whilst State Socialism is impracticable as a system of real Socialism, it is indeed possible if its advocates had their way, that all matters of general interest and more and more of private interest too would pass under the control of the State; whether it be a little more democratised or not, it does not matter, for we reject Democracy as well as Absolutism. Authority is equally hateful to us whether exercised by many, or by few, or by one. The last remnant of free initiative and self-reliance would be crushed under the hells of the State, and the emancipation of the workers would be far off as ever. State Socialism has indeed strengthened the decaying faith in, and renewed the prestige of, the State.

      All we Anarchists want is equal freedom for all. The workers to provide for their own affairs by voluntary arrangements amongst themselves. This leads us to a consideration of the economic basis of the state of things we desire to bring about, and here we avow ourselves Communists.

      Everybody has different faculties and abilities for work, and different wants and desires for the various necessities of life and leisure. These inclinations and wants require full satisfaction, but can only receive it in a state of freedom. Everybody supposing his faculties to be properly developed can best judge what is best for himself. Rules and regulations would hinder and make him a fettered, incomplete being who necessarily finds no pleasure in work forced upon him. But under Anarchy he would associate voluntarily with others to do the work he is best fitted to do, and would satisfy his wants in proportion to his needs from the common stock, the result of their common labor.

      Cut-throat competition for the bare necessities of life would be done away with, leaving many matters of a more individual, private and intimate character, in which the free man would find opportunity for peaceful and harmonious emulation, and thereby develop his faculties in the highest possible degree.

      One of the stock objections against Anarchist Communism is that no one would work. We reply that to- day work is viewed with disfavor and neglected by all who can possibly exist without it because it has to be carried on under the most disadvantageous conditions and is, moreover, looked upon as degrading. The worker earning his food by hard labor and ceaseless toil is a pariah, the outcast of society, while the idler who never does an hours work in his life is admired and glorified, and spends his days in luxurious ease amongst pleasant surroundings. We believe that under Anarchism everybody would be willing to work; work being freed from the badge of dishonor now associated with it will have become a labor of love, and the free man will feel ashamed to eat food he has not earned. But as to some atavistic remnants of modern capitalist society that would only work if forced? Well, nobody would want us to retard the emancipation of the immense mass of mankind on account of these few unsocial beings who may or may not exist then. Left to themselves and scorned by everyone they would soon come to their senses and work.

      We cannot further enter here into the arguments which show the tendency of a development into Free Communism, and we refer to our literature on the subject. (See Kropotkin's "Anarchism: its Basis and Principles." Freedom Pamphlets, No. 4, etc.)

      Anarchist society will consist of a great number of groups devoted each to the production of certain commodities free of access to all, and in local and interlocal contact with other groups to agree and make arrangements for purposes of exchange. With regard to the first necessities of life, food, clothes, shelter, education, Free Communism would be carried out thoroughly. All secondary matters would be left to a mutual agreement in the most varied ways. There would remain in such a society full freedom for the Individualist as long as he did not develop any monopolistic tendencies.


      These are our principles; let us consider the means to realise them.

      Here we are met by the cry "Dynamiters", "Assassins", "Fiends", etc. Let us see who chiefly utter these cries.

      The same people who, by colliery disasters, the ensuring of rotten ships, fires in death-trap-houses, railway accidents caused by overwork, etc., daily massacre more people than the Anarchists of all countries ever killed. The same people who are ready at any moment to have the natives of any country slaughtered, simply to rob them, who are overjoyed at the butchery of the Chinese War, which will enable them to make fresh profit, who are slowly starving and killing the millions of workers, whose lives are shortened by overwork, adulterated food, and overcrowding slums. These people have, in our eyes, no voice when the question of humanity is considered. They may abuse and insult us just as they like. The worst thing that could happen to us, indeed, would be to win their approbation, to be petted by them as the respectable labor politicians are.

      Some well-meaning, but rather weak-minded people too, are misled by these cries. To these we say come and study our movement and gain a knowledge of its history and personalities, and you will find that every act of revolt is but a reply to a hundred, nay, a thousand villianeous crimes committed by the governing classes against us and against the workers in general. You will find that those who did these acts were the very best, the most human, unselfish, self-sacrificing of our comrades, who threw their lives away, meeting death or imprisonment in the hope that their acts would sow the seed of revolt, that they might show the way and wake an echo, by their deeds of rebellion, in the victims of the present system.

      With the specific mode of action of anyone we have nothing to do. Anarchists advocate the propagation of their ideas by all means that lead to that end, and everyone is the best judge of his own actions. No one is required to do anything that is against his own inclination. Experience is in this as in other matters the best teacher, and the necessary experience can only be gained through entire freedom of action.

      Thus the means which we would adopt embrace all that furthers our cause, and exclude all that will damage it. The decision of what is good or harmful must be left to persons or groups who choose to work together.

      Nothing is more contrary to the real spirit of Anarchy than uniformity and intolerance. Freedom of development implies difference of development, hence difference of ideas and actions. Every person is likely to be open to a different kind of argument, so propaganda cannot be diversified enough if we want to touch all. We want it to pervade and penetrate all the utterances of life, social and political, domestic and artistic, educational and recreational. There should be propaganda by word and action, the platform and the press, the street corner, the workshop, and the domestic circle, acts of revolt, and the example of our own lives as free men. Those who agree with each other may co-operate; otherwise they should prefer to work each on his own lines to trying to persuade one the other of the superiority of his own method.

      Organisation arises from the conciousness that, for a certain purpose, the co-operation of several forces is necessary. When this purpose is achieved the necessity for co-operation has ceased, and each force reassumes its previous independence, ready for other co-operation and combination if necessary. This is organisation in the Anarchist sense - ever varying, or, if necessary, continuous combinations of the elements that are considered to be the most suitable for the particular purpose on hand, and refers not only to the economical and industrial relations between man and man, but also to the sexual relations between man and woman, without which a harmonious social life is impossible.

      These views differ immensely from those held by the believers in authority, who advocate permanent organisations with chiefs or councils elected by the majority, and who put all their trust in these institutions. The more they centralise these organisations and introduce stringent rules and regulations to preserve order and discipline, the more they will fail to achieve their object. In such organisations we see only obstacles to the free initiative and action of individuals, hot-beds of ambition, self seeking and rotten beliefs in authority etc. That means, we see in them agents of reaction to keep the people in continued ignorance of their own interests.

      We do not therefore discourage workingmen from organisation, but such organisations could only be free groups of men and women with the same aims for identical purposes, disbanding when the object in view is achieved.

      This brings us to the question of the advisability of Anarchists to join Trade Unions, not the question of the membership of Unions which may be a necessity for them as the case stands, but the question of propaganda in them. Anarchists do not wish to isolate themselves and Unions may be useful as a place to meet their fellow workers. But whether Unions should be formed by Anarchists is entirely dependent on the particular case. For we do not consider Trades Unionism as at present constituted as a serious force to overthrow the system, but only as a means to get a little better provision for the workers under the present conditions. Therefore they cannot be carried on without dealing with immediate so-called practical questions, which are never settled without compromises, as all members are not Anarchists.

      In Unions the General Strike might form a proper subject to start the propaganda, and such a strike, though in itself not effective as a remedy, would probably bring about revolutionary situations which would advance the march of events in an unprecedented way. To speak plainly, we advocate the General Strike as a means to set the ball rolling: who knows whether it may not lead to the Social Revolution, which we all desire as the only thing that can help us.

      The Social Revolution, as we conceive it, would consist in the paralysation of all existing authoritarian institutions and organisations, the prevention of new organisations of this character, the expropriation of the present exploiters of labor, and in the rearrangement of relations between men on the basis of voluntary agreements. This will appear to some to be rather a large program, but logical thinking will convince them of the fact that every one of these points is the necessary consequence of the others, and that they can only be carried out altogether, or not at all. For what is really impracticable are not full measures, but those half- hearted measures - so-called reforms - which pretend to do away with a part of the existing misery, whilst the root remains intact and makes the whole reform futile and useless.

      These then are our means of propaganda, and we trust they are manifold enough to allow everybody full scope for his energies who chooses his place amongst us. The leading idea of our propaganda must always be defiance and destruction of the principle of authority in all its forms and disguises - full scope for freedom, the basis and condition of all human development and progress.


      In conclusion, let us consider briefly the remedies proposed by the other parties - useless as they are, as the ever-increasing misery around us abundantly shows.

      The State Socialist parties, apart from a few Socialists pure and simple who, if they were true to the foundations of their opinions, would come over to us, have of late become entirely parties for advocating political action. They believe in sending the right man to Parliament, and we have the choice between the chosen of the I.L.P., of the Fabians, and of the S.D.F. We do not consider their minor differences: what is the principle of political action worth? - is the question we ask. It is intended to bring about these social changes. Some palliatives may be adopted, but the system will continue to exist; for these labor parties make the workers believe in constitutional means, in the leadership and worship of men; in short, they destroy their self-reliance and self-respect, and do for them that which religion does - make them expect everything from others, nothing from themselves. The history of the labor movement in Europe and America shows the greater these parties become the less advanced their leaders grow and the less is achieved by these bulky, cast-iron organisations with no room for freedom left in them.

      We have no more belief in Trades Unions as such than in political action, yet we prefer those Unionists, who rely upon their own action to those who cry for State help. Our propaganda might sometimes use this question as a starting point.

      The Co-operative movement can only benefit a few who remain unnoticed among the general misery. Productive Co-operation on a large scale would have to compete with capitalism, which ruthlessly cuts down wages and gets a supply of cheap labor from the unemployed. Co-operators would have to work on similar lines, those of the greatest possible exploitation of labor and that will be no remedy for the needs of labor, or they would be crushed by the capitalist competition, being in fact the first victims of a commercial crisis. Thus on a large scale Co-operation is impracticable, and those who take part in it in is present form are only too often estranged from the general labor movement. So we consider Co-operators as workers who are no essential factor in the coming struggle.

      The meanest and most repulsive "friends" of the workers are the Teetotalers, Malthusianists, and the advocates of thrift and saving, who propound each his particular crochet as an infallible remedy for poverty. They want the workers to give up the small mites of, however adulterated and paltry, pleasure and enjoyment that are left to them. "Hypocrisy is the compliment vice pays to virtue", the proverb says, and the other parties make at any rate promises of better things, but these want to make life still more dreary and cheerless. Economically they are utterly wrong. If all were content to live as Coolies do, on a handful of rice per day, wages would be lowered by competition to the level of Coolie wages - a few pence per day. We want the standard of the workers' living raised, not lowered, and all the things to which these "friends" object to a real, full, human life.

      We need not dwell on all the cranks who have cut and dried remedies like the Free Currency advocates, who ignore the principle of every society with private property: "No property, no credit". To be benefited by money cheques, it would be necessary to possess some kind of portable or realisable property to be given in exchange for the cheques or to have them secured on. Nothing would be altered by them, they could simply perpetuate the worst evils of the present system in a more aggravated form. To the worker who has no property but his labor to dispatch of, in times when work is slack and labor therefore not in demand, they would offer no resource whatever, and he would still be obliged to suffer and to starve. To make the remedy proportionate to the evil proposed to be cured, it would be requisite to abolish all private property and make the land and all it contains, together with all the implements of production, common property - that is, to introduce Communism, where money and money cheques will have become equally useless.

      As you will have seen, Anarchism does not preach anything contrary to the principles which have always inspired men to strive for freedom and right. It would indeed be absurd to try and impose something new upon mankind. No! Anarchism is nothing but the full acknowledgment of the realisation of the principle that freedom is at the root of sound natural development. Nature knows no outside laws, no external powers, and only follows her own inward forces of attraction or repulsion. Everything is the result of the existing forces and tendencies, and this result becomes again in turn the cause of the next thing following. In its childhood, humanity suffered from the ignorance of this cause, and suffers still by being trodden under the heel of imaginary celestial and human authority (both arising from the same sources - ignorance and the fear of the unknown). All progress has been made by fighting and defying authority. Great men in history - men who have done real work, that is, work useful for the progress of the human race by breaking and defying laws and regulations apparently made for everlasting time - showed mankind new roads, opened new ground. There were rebels, and the last in this series - those who wish not only to be free themselves but who saw that which before them men did not see so clearly, that to be free ourselves we must be surrounded by free men; that the slavery of the meanest human being is our own slavery. Those last rebels for freedom and progress are the Anarchists of all countries, and in solidarity with them we appeal to you.

      Study our principles, our movement, and if they convince you join us in our struggle against authority and exploitation, for freedom and happiness for all.
"""

if __name__ == '__main__':
  unittest.main()

 
